import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { localEnvironment, assertSafeArtifacts } from './artifact-security.mjs';
const env = { ...process.env };
for (const key of Object.keys(localEnvironment())) env[key] = '';
for (const key of Object.keys(env)) if (/^(AUTH_|MONGODB_|CLOUDFLARE_API_TOKEN$)/.test(key)) env[key] = '';
const require = createRequire(new URL('../webapp/package.json', import.meta.url));
const result = spawnSync(process.execPath, [require.resolve('next/dist/bin/next'), 'build'], { cwd: fileURLToPath(new URL('../webapp/', import.meta.url)), env, stdio: 'inherit', windowsHide: true });
if (result.status !== 0) process.exit(result.status ?? 1);
assertSafeArtifacts();
